export const blogs = [
  {
    heading: 'How i lost my virginity',
    text: 'lorem Ipsum what the fuck',
    image: 'assets/face.png',
    date: '20.02.2020',
    time: '20:00',
    place: 'vienna',
  },
  {
    heading: 'How i lerned to code',
    text: 'lorem',
    image: 'assets/code.jpg',
    date: '20.02.2020',
    time: '20:00',
    place: 'vienna',
  },
  {
    heading: 'How i lost my virginity',
    text: 'lorem',
    image: 'assets/face.jpg',
    date: '20.02.2020',
    time: '20:00',
    place: 'vienna',
  },
  {
    heading: 'How i lost my virginity',
    text: 'lorem',
    image: 'assets/face.jpg',
    date: '20.02.2020',
    time: '20:00',
    place: 'vienna',
  },
  {
    heading: 'How i lost my virginity',
    text: 'lorem',
    image: 'assets/face.jpg',
    date: '20.02.2020',
    time: '20:00',
    place: 'vienna',
  },
  {
    heading: 'How i lost my virginity',
    text: 'lorem',
    image: 'assets/face.jpg',
    date: '20.02.2020',
    time: '20:00',
    place: 'vienna',
  },
];
